(() => {
'use strict';
const sb = supabase.createClient(window.SUPABASE_URL, window.SUPABASE_PUBLISHABLE_KEY);
const $ = id => document.getElementById(id);
let cache = {teachers:[], institutions:[], visits:[], seminars:[], dispatches:[]};
const today = () => new Date().toISOString().slice(0,10);
const fmtDate = v => v ? new Date(v+'T00:00:00').toLocaleDateString('ar-DZ') : '—';
const esc = v => String(v ?? '').replace(/[&<>\"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
function openModal(id){const e=$(id);if(e)e.hidden=false}
function closeModal(id){const e=$(id);if(e)e.hidden=true}
function formObj(f){return Object.fromEntries(new FormData(f).entries())}
function err(msg){console.error(msg);alert(msg)}
function showLogin(){if($('loginView'))$('loginView').hidden=false;if($('dashboardView'))$('dashboardView').hidden=true}
function showApp(){if($('loginView'))$('loginView').hidden=true;if($('dashboardView'))$('dashboardView').hidden=false;loadAll()}
function loginError(msg){const e=$('loginError');if(e){e.textContent=msg||'';e.style.display=msg?'block':'none'}}

async function init(){
  try{
    const {data,error}=await sb.auth.getSession();
    if(error){loginError('تعذر الاتصال بخدمة تسجيل الدخول: '+error.message);return}
    sb.auth.onAuthStateChange((event,session)=>{if(session)showApp();else if(event==='SIGNED_OUT')showLogin()});
    if(data.session)showApp();else showLogin();
  }catch(e){loginError('حدث خطأ في تشغيل المنصة: '+e.message)}
}

$('loginForm')?.addEventListener('submit',async e=>{
  e.preventDefault();
  const btn=e.submitter||e.target.querySelector('button');
  const email=$('email').value.trim(), password=$('password').value;
  loginError(''); if(btn){btn.disabled=true;btn.textContent='جارٍ تسجيل الدخول...'}
  try{
    const {data,error}=await sb.auth.signInWithPassword({email,password});
    if(error){loginError(/invalid login credentials/i.test(error.message)?'البريد الإلكتروني أو كلمة المرور غير صحيحة.':error.message);return}
    if(data?.session)showApp();
  }catch(e){loginError('تعذر تسجيل الدخول: '+e.message)}
  finally{if(btn){btn.disabled=false;btn.textContent='تسجيل الدخول'}}
});
$('logoutBtn')?.addEventListener('click',()=>sb.auth.signOut());
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.section').forEach(x=>x.hidden=true);$(b.dataset.section).hidden=false}));
$('teacherSearch')?.addEventListener('input',()=>renderTeachers());

async function loadAll(){
  try{
    const [t,i,v,s,d]=await Promise.all([
      sb.from('teachers').select('*,institutions(name,municipality,administrative_district)').order('last_name'),
      sb.from('institutions').select('*').order('name'),
      sb.from('visits').select('*,teachers(first_name,last_name,employee_number,rank,grade,appointment_date),institutions(name,municipality,administrative_district)').order('scheduled_date'),
      sb.from('seminars').select('*').order('seminar_date'),
      sb.from('dispatches').select('*').order('dispatch_date',{ascending:false})
    ]);
    const bad=[t,i,v,s,d].find(x=>x.error);if(bad){console.error(bad.error);return}
    cache={teachers:t.data||[],institutions:i.data||[],visits:v.data||[],seminars:s.data||[],dispatches:d.data||[]};
    $('countTeachers').textContent=cache.teachers.length;$('countInstitutions').textContent=cache.institutions.length;$('countVisits').textContent=cache.visits.length;$('countSeminars').textContent=cache.seminars.length;
    fillSelects();renderTeachers();renderInstitutions();renderVisits();renderSeminars();renderDispatches();renderUpcoming();
  }catch(e){console.error('loadAll',e)}
}
function renderTeachers(){const q=($('teacherSearch')?.value||'').toLowerCase().trim();const r=cache.teachers.filter(x=>`${x.first_name||''} ${x.last_name||''} ${x.employee_number||''} ${x.institutions?.name||''}`.toLowerCase().includes(q));$('teachersTable').innerHTML=r.length?`<div class="table-wrap"><table><thead><tr><th>الأستاذ</th><th>رقم الموظف</th><th>المؤسسة</th><th>الرتبة</th><th>الدرجة</th><th>آخر تفتيش</th><th>الإجراءات</th></tr></thead><tbody>${r.map(x=>`<tr><td><button class="link-btn" onclick="viewTeacher('${x.id}')">${esc(x.last_name+' '+x.first_name)}</button></td><td>${esc(x.employee_number||'—')}</td><td>${esc(x.institutions?.name||'—')}</td><td>${esc(x.rank||'—')}</td><td>${esc(x.grade||'—')}</td><td>${fmtDate(x.last_inspection_date)}</td><td><div class="actions"><button class="small-btn" onclick="viewTeacher('${x.id}')">الملف</button><button class="small-btn" onclick="editTeacher('${x.id}')">تعديل</button><button class="small-btn danger" onclick="deleteTeacher('${x.id}')">حذف</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا يوجد أساتذة مطابقون للبحث.</div>'}
function renderInstitutions(){$('institutionsTable').innerHTML=cache.institutions.length?`<div class="table-wrap"><table><thead><tr><th>المؤسسة</th><th>النوع</th><th>المقاطعة الإدارية</th><th>البلدية</th><th>المدير</th><th>الهاتف</th></tr></thead><tbody>${cache.institutions.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.institution_type)}</td><td>${esc(x.administrative_district||'—')}</td><td>${esc(x.municipality||'—')}</td><td>${esc(x.director_name||'—')}</td><td>${esc(x.phone||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد مؤسسات بعد.</div>'}
function renderVisits(){$('visitsTable').innerHTML=cache.visits.length?`<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>الأستاذ</th><th>المؤسسة</th><th>النوع</th><th>المكان</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>${cache.visits.map(x=>`<tr><td>${fmtDate(x.scheduled_date)}</td><td>${esc((x.teachers?.last_name||'')+' '+(x.teachers?.first_name||''))}</td><td>${esc(x.institutions?.name||'—')}</td><td><span class="badge">${esc(x.visit_type||'—')}</span></td><td>${esc(x.field_location||'الملعب / الفضاء الرياضي')}</td><td>${esc(x.status||'مبرمجة')}</td><td><div class="actions"><button class="small-btn" onclick="openReport('${x.id}')">التقرير</button><button class="small-btn" onclick="editVisit('${x.id}')">تعديل</button><button class="small-btn danger" onclick="deleteVisit('${x.id}')">حذف</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد زيارات مبرمجة بعد.</div>'}
function renderSeminars(){$('seminarsTable').innerHTML=cache.seminars.length?`<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>العنوان</th><th>المكان</th><th>الحالة</th></tr></thead><tbody>${cache.seminars.map(x=>`<tr><td>${fmtDate(x.seminar_date)}</td><td>${esc(x.title)}</td><td>${esc(x.location||'—')}</td><td>${esc(x.status||'مبرمجة')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد ندوات بعد.</div>'}
function renderDispatches(){$('dispatchesTable').innerHTML=cache.dispatches.length?`<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>رقم الإرسال</th><th>الجهة</th><th>الموضوع</th></tr></thead><tbody>${cache.dispatches.map(x=>`<tr><td>${fmtDate(x.dispatch_date)}</td><td>${esc(x.dispatch_number||'—')}</td><td>${esc(x.recipient||'—')}</td><td>${esc(x.subject||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد إرساليات بعد.</div>'}
function renderUpcoming(){const r=cache.visits.filter(x=>x.scheduled_date>=today()).slice(0,6);$('upcomingVisits').innerHTML=r.length?'<ul class="upcoming">'+r.map(x=>`<li><b>${fmtDate(x.scheduled_date)}</b> — ${esc((x.teachers?.last_name||'')+' '+(x.teachers?.first_name||''))} — ${esc(x.institutions?.name||'')} — ${esc(x.visit_type||'')}</li>`).join('')+'</ul>':'<div class="empty">لا توجد زيارات قادمة.</div>'}
function fillSelects(){$('teacherInstitution').innerHTML='<option value="">— اختر المؤسسة —</option>'+cache.institutions.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('visitInstitution').innerHTML='<option value="">— اختر المؤسسة —</option>'+cache.institutions.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('visitTeacher').innerHTML='<option value="">— اختر الأستاذ —</option>'+cache.teachers.map(x=>`<option value="${x.id}">${esc(x.last_name+' '+x.first_name)} — ${esc(x.employee_number||'')}</option>`).join('')}
function resetTeacherForm(){$('teacherForm').reset();$('teacherId').value='';$('teacherModalTitle').textContent='إضافة أستاذ';$('teacherEmployeeNumber').textContent='يُنشأ آلياً عند الحفظ'}
window.openNewTeacherModal=()=>{resetTeacherForm();openModal('teacherModal')};
window.editTeacher=id=>{const t=cache.teachers.find(x=>x.id===id);if(!t)return;$('teacherId').value=t.id;$('teacherModalTitle').textContent='تعديل ملف الأستاذ';$('teacherEmployeeNumber').textContent=t.employee_number||'—';[['teacherLastName',t.last_name],['teacherFirstName',t.first_name],['teacherRank',t.rank],['teacherGrade',t.grade],['teacherAppointmentDate',t.appointment_date],['teacherPhone',t.phone],['teacherEmail',t.email],['teacherMunicipality',t.municipality],['teacherNotes',t.notes]].forEach(([i,v])=>$(i).value=v||'');$('teacherInstitution').value=t.institution_id||'';openModal('teacherModal')};
window.viewTeacher=id=>{const t=cache.teachers.find(x=>x.id===id);if(!t)return;const vs=cache.visits.filter(v=>v.teacher_id===id);$('teacherProfile').innerHTML=`<div class="profile-head"><div class="profile-avatar">${esc((t.last_name||'').charAt(0))}</div><div><h2>${esc(t.last_name+' '+t.first_name)}</h2><p>${esc(t.rank||'أستاذ التربية البدنية والرياضية')} — ${esc(t.institutions?.name||'دون مؤسسة')}</p><span class="badge">${esc(t.employee_number||'رقم غير متوفر')}</span></div></div><div class="profile-actions"><button class="primary" onclick="editTeacher('${id}');closeModal('teacherProfileModal')">تعديل الملف</button><button class="ghost" onclick="openVisitForTeacher('${id}')">برمجة زيارة</button></div><div class="profile-grid"><div><span>الرتبة</span><b>${esc(t.rank||'—')}</b></div><div><span>الدرجة</span><b>${esc(t.grade||'—')}</b></div><div><span>المؤسسة</span><b>${esc(t.institutions?.name||'—')}</b></div><div><span>البلدية</span><b>${esc(t.municipality||t.institutions?.municipality||'—')}</b></div><div><span>تاريخ التعيين</span><b>${fmtDate(t.appointment_date)}</b></div><div><span>آخر تفتيش</span><b>${fmtDate(t.last_inspection_date)}</b></div><div><span>آخر علامة</span><b>${t.last_inspection_score??'—'}</b></div><div><span>الهاتف</span><b>${esc(t.phone||'—')}</b></div></div><div class="panel profile-panel"><h3>سجل الزيارات (${vs.length})</h3>${vs.length?`<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>النوع</th><th>المكان</th><th>الحالة</th><th>التقرير</th></tr></thead><tbody>${vs.map(v=>`<tr><td>${fmtDate(v.scheduled_date)}</td><td>${esc(v.visit_type)}</td><td>${esc(v.field_location||'الملعب / الفضاء الرياضي')}</td><td>${esc(v.status||'مبرمجة')}</td><td><button class="small-btn" onclick="openReport('${v.id}')">فتح</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد زيارات.</div>'}</div>`;openModal('teacherProfileModal')};
window.deleteTeacher=async id=>{const t=cache.teachers.find(x=>x.id===id);if(!t||!confirm(`هل تريد حذف ملف الأستاذ ${t.last_name} ${t.first_name}؟`))return;const{error}=await sb.from('teachers').delete().eq('id',id);if(error)return err('تعذر الحذف: '+error.message);loadAll()};
function resetVisitForm(){$('visitForm').reset();$('visitId').value='';$('visitModalTitle').textContent='برمجة زيارة';$('visitSaveBtn').textContent='حفظ';$('visitLocation').value='الملعب / الفضاء الرياضي';$('visitType').value='توجيهية'}
window.openNewVisitModal=()=>{resetVisitForm();openModal('visitModal')};
window.openVisitForTeacher=id=>{closeModal('teacherProfileModal');resetVisitForm();$('visitTeacher').value=id;const t=cache.teachers.find(x=>x.id===id);if(t)$('visitInstitution').value=t.institution_id||'';openModal('visitModal')};
window.editVisit=id=>{const v=cache.visits.find(x=>x.id===id);if(!v)return;$('visitId').value=v.id;$('visitTeacher').value=v.teacher_id||'';$('visitInstitution').value=v.institution_id||'';$('visitDate').value=v.scheduled_date||'';$('visitTime').value=v.scheduled_time||'';$('visitType').value=v.visit_type||'توجيهية';$('visitLocation').value=v.field_location||'الملعب / الفضاء الرياضي';$('visitObjective').value=v.objective||'';$('visitModalTitle').textContent='تعديل الزيارة';$('visitSaveBtn').textContent='حفظ التعديلات';openModal('visitModal')};
window.deleteVisit=async id=>{if(!confirm('هل تريد حذف هذه الزيارة؟'))return;const{error}=await sb.from('visits').delete().eq('id',id);if(error)return err('تعذر الحذف: '+error.message);loadAll()};
window.openReport=async visitId=>{const v=cache.visits.find(x=>x.id===visitId);if(!v)return;const t=cache.teachers.find(x=>x.id===v.teacher_id);$('reportForm').reset();$('reportId').value='';$('reportVisitId').value=visitId;$('reportInspectionDate').value=v.scheduled_date||today();$('reportTeacherRank').value=t?.rank||'';$('reportTeacherGrade').value=t?.grade||'';$('reportAppointmentDate').value=t?.appointment_date||'';if($('reportTeacherSignature'))$('reportTeacherSignature').value=t?`${t.last_name} ${t.first_name}`:'';$('reportHeader').innerHTML=`<div class="report-title"><h2>تقرير الزيارة التربوية</h2><p>${esc(t?.last_name||'')} ${esc(t?.first_name||'')}</p><span>${esc(v.institutions?.name||'')} | ${esc(v.field_location||'الملعب / الفضاء الرياضي')} | ${fmtDate(v.scheduled_date)}</span><div class="report-actions"><button type="button" class="primary" onclick="printCurrentReport()">طباعة / PDF</button></div></div>`;const{data,error}=await sb.from('visit_reports').select('*').eq('visit_id',visitId).maybeSingle();if(error)console.warn(error);if(data){Object.entries(data).forEach(([k,val])=>{const el=document.querySelector(`#reportForm [name="${k}"]`);if(el&&val!==null)el.value=val});$('reportId').value=data.id;$('reportVisitId').value=visitId}openModal('reportModal')};
window.printCurrentReport=()=>{const card=$('reportModal')?.querySelector('.modal-card');if(!card)return;const w=window.open('','_blank');if(!w)return;w.document.write(`<html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>تقرير الزيارة التربوية</title><style>@page{size:A4;margin:14mm}body{font-family:Tahoma,Arial,sans-serif;color:#111;line-height:1.7;font-size:12px}.close,.report-actions,button{display:none!important}.report-section{border:1px solid #bbb;padding:12px;margin:10px 0}.report-section h3{margin:0 0 10px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.form-grid .full{grid-column:1/-1}label{font-weight:bold}input,select,textarea{display:block;width:100%;border:0;background:#fff;font:inherit;box-sizing:border-box}.report-title{text-align:center;border-bottom:2px solid #111;padding-bottom:10px}</style></head><body>${card.innerHTML}</body></html>`);w.document.close();setTimeout(()=>{w.focus();w.print()},500)};

$('teacherForm')?.addEventListener('submit',async e=>{e.preventDefault();const o=formObj(e.target),id=o.id;delete o.id;const r=id?await sb.from('teachers').update(o).eq('id',id):await sb.from('teachers').insert(o);if(r.error)return err('تعذر حفظ الأستاذ: '+r.error.message);closeModal('teacherModal');loadAll()});
$('institutionForm')?.addEventListener('submit',async e=>{e.preventDefault();const o=formObj(e.target);const{error}=await sb.from('institutions').insert(o);if(error)return err('تعذر حفظ المؤسسة: '+error.message);closeModal('institutionModal');e.target.reset();loadAll()});
$('visitForm')?.addEventListener('submit',async e=>{e.preventDefault();const o=formObj(e.target),id=o.id;delete o.id;if(!o.institution_id)o.institution_id=null;if(!o.scheduled_time)o.scheduled_time=null;const r=id?await sb.from('visits').update(o).eq('id',id):await sb.from('visits').insert(o);if(r.error)return err('تعذر حفظ الزيارة: '+r.error.message);closeModal('visitModal');resetVisitForm();loadAll()});
$('reportForm')?.addEventListener('submit',async e=>{e.preventDefault();const o=formObj(e.target),id=o.id,visitId=o.visit_id;delete o.id;['pupils_count','previous_score','score'].forEach(k=>{if(k in o)o[k]=o[k]===''?null:Number(o[k])});const r=id?await sb.from('visit_reports').update(o).eq('id',id):await sb.from('visit_reports').insert(o);if(r.error)return err('تعذر حفظ التقرير: '+r.error.message);await sb.from('visits').update({status:'منجزة'}).eq('id',visitId);const v=cache.visits.find(x=>x.id===visitId);if(v?.teacher_id)await sb.from('teachers').update({last_inspection_date:o.inspection_date||today(),last_inspection_score:o.score}).eq('id',v.teacher_id);alert('تم حفظ التقرير بنجاح.');closeModal('reportModal');loadAll()});
$('seminarForm')?.addEventListener('submit',async e=>{e.preventDefault();const{error}=await sb.from('seminars').insert(formObj(e.target));if(error)return err('تعذر حفظ الندوة: '+error.message);closeModal('seminarModal');e.target.reset();loadAll()});
$('dispatchForm')?.addEventListener('submit',async e=>{e.preventDefault();const{error}=await sb.from('dispatches').insert(formObj(e.target));if(error)return err('تعذر حفظ جدول الإرسال: '+error.message);closeModal('dispatchModal');e.target.reset();loadAll()});
window.openModal=openModal;window.closeModal=closeModal;
init();
})();
