const sb = supabase.createClient(window.SUPABASE_URL, window.SUPABASE_PUBLISHABLE_KEY);
const $ = id => document.getElementById(id);
let cache = {teachers:[],institutions:[],visits:[],seminars:[],dispatches:[]};
function openModal(id){const el=$(id);if(el)el.hidden=false} function closeModal(id){const el=$(id);if(el)el.hidden=true}
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))} function fmtDate(v){return v?new Date(v+'T00:00:00').toLocaleDateString('ar-DZ'):'—'} function today(){return new Date().toISOString().slice(0,10)}
function showLoginError(message){const box=$('loginError');if(!box)return;box.textContent=message||'';box.style.display=message?'block':'none';box.style.padding=message?'10px 12px':'0';box.style.marginTop=message?'12px':'0';box.style.background=message?'#fef2f2':'transparent';box.style.border=message?'1px solid #fecaca':'0';box.style.borderRadius=message?'8px':'0'} function showLogin(){$('loginView').hidden=false;$('dashboardView').hidden=true} function showApp(){$('loginView').hidden=true;$('dashboardView').hidden=false;loadAll()}
async function init(){try{if(!window.SUPABASE_URL||!window.SUPABASE_PUBLISHABLE_KEY||window.SUPABASE_PUBLISHABLE_KEY.includes('ضع_')){showLoginError('إعدادات الاتصال بقاعدة البيانات غير مكتملة.');return}sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session)showApp();else if(event==='SIGNED_OUT')showLogin()});const {data,error}=await sb.auth.getSession();if(error){showLoginError('تعذر الاتصال بخدمة تسجيل الدخول: '+error.message);return}if(data?.session)showApp();else showLogin()}catch(err){showLoginError('حدث خطأ في تشغيل المنصة: '+(err.message||err))}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter||e.target.querySelector('button[type="submit"]');const email=$('email').value.trim();const password=$('password').value;showLoginError('');if(!email||!password){showLoginError('أدخل البريد الإلكتروني وكلمة المرور.');return}if(btn){btn.disabled=true;btn.textContent='جارٍ تسجيل الدخول...'}try{const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){let msg=error.message||'بيانات الدخول غير صحيحة.';if(/invalid login credentials/i.test(msg))msg='البريد الإلكتروني أو كلمة المرور غير صحيحة.';if(/email not confirmed/i.test(msg))msg='الحساب موجود، لكن البريد الإلكتروني غير مؤكد.';showLoginError(msg);return}if(!data?.session){showLoginError('تم تسجيل الدخول دون إنشاء جلسة.');return}showApp()}catch(err){showLoginError('تعذر تنفيذ تسجيل الدخول: '+(err.message||err))}finally{if(btn){btn.disabled=false;btn.textContent='تسجيل الدخول'}}});
$('logoutBtn').onclick=async()=>{const {error}=await sb.auth.signOut();if(error)showLoginError('تعذر تسجيل الخروج: '+error.message)}; document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.section').forEach(x=>x.hidden=true);$(b.dataset.section).hidden=false});
async function loadAll(){try{const [t,i,v,s,d]=await Promise.all([sb.from('teachers').select('*,institutions(name,municipality,administrative_district)').order('last_name'),sb.from('institutions').select('*').order('name'),sb.from('visits').select('*,teachers(first_name,last_name,employee_number),institutions(name,municipality,administrative_district)').order('scheduled_date'),sb.from('seminars').select('*').order('seminar_date'),sb.from('dispatches').select('*').order('dispatch_date',{ascending:false})]);cache={teachers:t.data||[],institutions:i.data||[],visits:v.data||[],seminars:s.data||[],dispatches:d.data||[]};const errors=[t,i,v,s,d].filter(x=>x.error);if(errors.length)console.error('Database errors',errors);$('countTeachers').textContent=cache.teachers.length;$('countInstitutions').textContent=cache.institutions.length;$('countVisits').textContent=cache.visits.length;$('countSeminars').textContent=cache.seminars.length;renderTeachers();renderInstitutions();renderVisits();renderSeminars();renderDispatches();fillSelects();renderUpcoming()}catch(err){console.error('loadAll error:',err)}}
function renderTeachers(){const q=($('teacherSearch')?.value||'').toLowerCase().trim();const rows=cache.teachers.filter(x=>`${x.first_name||''} ${x.last_name||''} ${x.employee_number||''} ${x.institutions?.name||''}`.toLowerCase().includes(q));$('teachersTable').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>الأستاذ</th><th>رقم الموظف</th><th>المؤسسة</th><th>الرتبة</th><th>الدرجة</th><th>آخر تفتيش</th><th>الإجراءات</th></tr></thead><tbody>${rows.map(x=>`<tr><td><button class="link-btn" onclick="viewTeacher('${x.id}')">${esc(x.last_name+' '+x.first_name)}</button></td><td>${esc(x.employee_number||'—')}</td><td>${esc(x.institutions?.name||'—')}</td><td>${esc(x.rank||'—')}</td><td>${esc(x.grade||'—')}</td><td>${fmtDate(x.last_inspection_date)}</td><td><div class="actions"><button class="small-btn" onclick="viewTeacher('${x.id}')">الملف</button><button class="small-btn" onclick="editTeacher('${x.id}')">تعديل</button><button class="small-btn danger" onclick="deleteTeacher('${x.id}')">حذف</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا يوجد أساتذة مطابقون للبحث.</div>'}
function renderInstitutions(){$('institutionsTable').innerHTML=cache.institutions.length?`<div class="table-wrap"><table><thead><tr><th>المؤسسة</th><th>النوع</th><th>المقاطعة الإدارية</th><th>البلدية</th><th>المدير</th><th>الهاتف</th></tr></thead><tbody>${cache.institutions.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.institution_type||'—')}</td><td>${esc(x.administrative_district||'—')}</td><td>${esc(x.municipality||'—')}</td><td>${esc(x.director_name||'—')}</td><td>${esc(x.phone||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد مؤسسات بعد.</div>'}
function renderVisits(){$('visitsTable').innerHTML=cache.visits.length?`<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>الأستاذ</th><th>المؤسسة</th><th>النوع</th><th>المكان</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>${cache.visits.map(x=>`<tr><td>${fmtDate(x.scheduled_date)}</td><td>${esc((x.teachers?.last_name||'')+' '+(x.teachers?.first_name||''))}</td><td>${esc(x.institutions?.name||'—')}</td><td><span class="badge">${esc(x.visit_type||'—')}</span></td><td>${esc(x.field_location||'الملعب / الفضاء الرياضي')}</td><td>${esc(x.status||'مجدولة')}</td><td><div class="actions"><button class="small-btn" onclick="editVisit('${x.id}')">تعديل</button><button class="small-btn danger" onclick="deleteVisit('${x.id}')">حذف</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد زيارات مبرمجة بعد.</div>'}
function renderSeminars(){$('seminarsTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>العنوان</th><th>المكان</th><th>الحالة</th></tr></thead><tbody>${cache.seminars.map(x=>`<tr><td>${fmtDate(x.seminar_date)}</td><td>${esc(x.title)}</td><td>${esc(x.location||'—')}</td><td><span class="badge">${esc(x.status||'مجدولة')}</span></td></tr>`).join('')}</tbody></table></div>`}
function renderDispatches(){$('dispatchesTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>رقم الإرسال</th><th>الجهة</th><th>الموضوع</th></tr></thead><tbody>${cache.dispatches.map(x=>`<tr><td>${fmtDate(x.dispatch_date)}</td><td>${esc(x.dispatch_number||'—')}</td><td>${esc(x.recipient||'—')}</td><td>${esc(x.subject||'—')}</td></tr>`).join('')}</tbody></table></div>`}
function renderUpcoming(){const v=cache.visits.filter(x=>x.scheduled_date>=today()).slice(0,6);$('upcomingVisits').innerHTML=v.length?'<ul class="upcoming">'+v.map(x=>`<li><b>${fmtDate(x.scheduled_date)}</b> — ${esc((x.teachers?.last_name||'')+' '+(x.teachers?.first_name||''))} — ${esc(x.institutions?.name||'')} — ${esc(x.visit_type||'')}</li>`).join('')+'</ul>':'<div class="empty">لا توجد زيارات قادمة.</div>'}
function fillSelects(){$('teacherInstitution').innerHTML='<option value="">— اختر المؤسسة —</option>'+cache.institutions.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('visitInstitution').innerHTML='<option value="">— اختر المؤسسة —</option>'+cache.institutions.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('visitTeacher').innerHTML='<option value="">— اختر الأستاذ —</option>'+cache.teachers.map(x=>`<option value="${x.id}">${esc(x.last_name+' '+x.first_name)} — ${esc(x.employee_number||'')}</option>`).join('')}
function formObj(form){return Object.fromEntries(new FormData(form).entries())}
function resetTeacherForm(){$('teacherForm').reset();$('teacherId').value='';$('teacherModalTitle').textContent='إضافة أستاذ';$('teacherEmployeeNumber').textContent='يُنشأ آلياً عند الحفظ'}
function openNewTeacherModal(){resetTeacherForm();openModal('teacherModal')}
function editTeacher(id){const t=cache.teachers.find(x=>x.id===id);if(!t)return;$('teacherId').value=t.id;$('teacherModalTitle').textContent='تعديل ملف الأستاذ';$('teacherEmployeeNumber').textContent=t.employee_number||'—';$('teacherLastName').value=t.last_name||'';$('teacherFirstName').value=t.first_name||'';$('teacherRank').value=t.rank||'';$('teacherGrade').value=t.grade||'';$('teacherInstitution').value=t.institution_id||'';$('teacherAppointmentDate').value=t.appointment_date||'';$('teacherPhone').value=t.phone||'';$('teacherEmail').value=t.email||'';$('teacherMunicipality').value=t.municipality||'';$('teacherNotes').value=t.notes||'';openModal('teacherModal')}
function viewTeacher(id){const t=cache.teachers.find(x=>x.id===id);if(!t)return;const visits=cache.visits.filter(v=>v.teacher_id===id).sort((a,b)=>(b.scheduled_date||'').localeCompare(a.scheduled_date||''));$('teacherProfile').innerHTML=`<div class="profile-head"><div class="profile-avatar">${esc((t.last_name||'').charAt(0))}</div><div><h2>${esc(t.last_name+' '+t.first_name)}</h2><p>${esc(t.rank||'أستاذ التربية البدنية والرياضية')} — ${esc(t.institutions?.name||'دون مؤسسة')}</p><span class="badge">${esc(t.employee_number||'رقم غير متوفر')}</span></div></div><div class="profile-actions"><button class="primary" onclick="editTeacher('${t.id}');closeModal('teacherProfileModal')">تعديل الملف</button><button class="ghost" onclick="openVisitForTeacher('${t.id}')">برمجة زيارة</button></div><div class="profile-grid"><div><span>رقم الموظف</span><b>${esc(t.employee_number||'—')}</b></div><div><span>الرتبة</span><b>${esc(t.rank||'—')}</b></div><div><span>الدرجة</span><b>${esc(t.grade||'—')}</b></div><div><span>المؤسسة</span><b>${esc(t.institutions?.name||'—')}</b></div><div><span>المقاطعة الإدارية</span><b>${esc(t.institutions?.administrative_district||'—')}</b></div><div><span>البلدية</span><b>${esc(t.municipality||t.institutions?.municipality||'—')}</b></div><div><span>تاريخ التعيين</span><b>${fmtDate(t.appointment_date)}</b></div><div><span>الهاتف</span><b>${esc(t.phone||'—')}</b></div><div><span>البريد الإلكتروني</span><b>${esc(t.email||'—')}</b></div><div><span>آخر تفتيش</span><b>${fmtDate(t.last_inspection_date)}</b></div></div><div class="panel profile-panel"><h3>سجل الزيارات (${visits.length})</h3>${visits.length?`<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>النوع</th><th>المؤسسة</th><th>المكان</th><th>الحالة</th></tr></thead><tbody>${visits.map(v=>`<tr><td>${fmtDate(v.scheduled_date)}</td><td>${esc(v.visit_type||'—')}</td><td>${esc(v.institutions?.name||'—')}</td><td>${esc(v.field_location||'الملعب / الفضاء الرياضي')}</td><td>${esc(v.status||'مجدولة')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد زيارات مسجلة لهذا الأستاذ.</div>'}</div><div class="panel profile-panel"><h3>ملاحظات</h3><p>${esc(t.notes||'لا توجد ملاحظات.')}</p></div>`;openModal('teacherProfileModal')}
async function deleteTeacher(id){const t=cache.teachers.find(x=>x.id===id);if(!t)return;if(!confirm(`هل أنت متأكد من حذف ملف الأستاذ «${t.last_name} ${t.first_name}»؟`))return;const {error}=await sb.from('teachers').delete().eq('id',id);if(error){alert('تعذر حذف الأستاذ: '+error.message);return}closeModal('teacherProfileModal');await loadAll()}
function resetVisitForm(){$('visitForm').reset();$('visitId').value='';$('visitModalTitle').textContent='برمجة زيارة';$('visitSaveBtn').textContent='حفظ';$('visitLocation').value='الملعب / الفضاء الرياضي';$('visitType').value='توجيهية'}
function openNewVisitModal(){resetVisitForm();openModal('visitModal')}
function openVisitForTeacher(id){closeModal('teacherProfileModal');resetVisitForm();fillSelects();$('visitTeacher').value=id;const t=cache.teachers.find(x=>x.id===id);if(t?.institution_id)$('visitInstitution').value=t.institution_id;openModal('visitModal')}
function editVisit(id){const v=cache.visits.find(x=>x.id===id);if(!v)return;$('visitId').value=v.id;$('visitModalTitle').textContent='تعديل الزيارة';$('visitSaveBtn').textContent='حفظ التعديلات';$('visitTeacher').value=v.teacher_id||'';$('visitInstitution').value=v.institution_id||'';$('visitDate').value=v.scheduled_date||'';$('visitTime').value=v.scheduled_time||'';$('visitType').value=v.visit_type||'توجيهية';$('visitLocation').value=v.field_location||'الملعب / الفضاء الرياضي';$('visitObjective').value=v.objective||'';openModal('visitModal')}
async function deleteVisit(id){const v=cache.visits.find(x=>x.id===id);if(!v)return;if(!confirm('هل تريد حذف هذه الزيارة؟'))return;const {error}=await sb.from('visits').delete().eq('id',id);if(error){alert('تعذر حذف الزيارة: '+error.message);return}await loadAll()}
$('teacherForm').addEventListener('submit',async e=>{e.preventDefault();const o=formObj(e.target);const id=o.id;delete o.id;delete o.employee_number;delete o.experience_years;const result=id?await sb.from('teachers').update(o).eq('id',id):await sb.from('teachers').insert(o);if(result.error){alert('تعذر حفظ ملف الأستاذ: '+result.error.message);return}closeModal('teacherModal');resetTeacherForm();await loadAll()});
$('institutionForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.from('institutions').insert(formObj(e.target));if(error){alert('تعذر إضافة المؤسسة: '+error.message);return}closeModal('institutionModal');e.target.reset();await loadAll()});
$('visitForm').addEventListener('submit',async e=>{e.preventDefault();const o=formObj(e.target);const id=o.id;delete o.id;if(!o.institution_id)o.institution_id=null;if(!o.scheduled_time)o.scheduled_time=null;const result=id?await sb.from('visits').update(o).eq('id',id):await sb.from('visits').insert(o);if(result.error){alert('تعذر حفظ الزيارة: '+result.error.message);return}closeModal('visitModal');resetVisitForm();await loadAll()});
$('seminarForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.from('seminars').insert(formObj(e.target));if(error){alert('تعذر إضافة الندوة: '+error.message);return}closeModal('seminarModal');e.target.reset();await loadAll()});
$('dispatchForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.from('dispatches').insert(formObj(e.target));if(error){alert('تعذر إضافة جدول الإرسال: '+error.message);return}closeModal('dispatchModal');e.target.reset();await loadAll()});
$('teacherSearch').addEventListener('input',renderTeachers);init();