(()=>{'use strict';
const DRIVE_SCOPE='https://www.googleapis.com/auth/drive.file';
let driveToken=null,tokenClient=null;
const $=id=>document.getElementById(id);
const CLIENT_ID=window.GOOGLE_DRIVE_CLIENT_ID||'';
function loadGIS(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.onload=resolve;s.onerror=()=>reject(new Error('تعذر تحميل خدمة Google.'));document.head.appendChild(s)})}
async function connectDrive(){
 if(!CLIENT_ID){alert('لم يتم إعداد Google Drive بعد. أضف Google OAuth Client ID في إعدادات المنصة.');return}
 try{await loadGIS();tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:DRIVE_SCOPE,callback:r=>{if(r.error){alert('تعذر منح صلاحية Google Drive.');return}driveToken=r.access_token;localStorage.setItem('driveConnected','1');updateDriveUI()}});tokenClient.requestAccessToken({prompt:driveToken?'':'consent'})}catch(e){alert(e.message||'تعذر الاتصال بـ Google Drive.')}
}
async function ensureFolder(){let q=encodeURIComponent("name='منصة مفتش المادة' and mimeType='application/vnd.google-apps.folder' and trashed=false");let r=await fetch('https://www.googleapis.com/drive/v3/files?q='+q+'&fields=files(id,name)',{headers:{Authorization:'Bearer '+driveToken}});if(!r.ok)throw Error('تعذر الوصول إلى Google Drive.');let d=await r.json();if(d.files?.[0])return d.files[0].id;let c=await fetch('https://www.googleapis.com/drive/v3/files',{method:'POST',headers:{Authorization:'Bearer '+driveToken,'Content-Type':'application/json'},body:JSON.stringify({name:'منصة مفتش المادة',mimeType:'application/vnd.google-apps.folder'})});if(!c.ok)throw Error('تعذر إنشاء مجلد المنصة.');return (await c.json()).id}
async function uploadDrive(file){if(!driveToken)throw Error('يرجى ربط Google Drive أولاً.');const parent=await ensureFolder();const meta={name:file.name,parents:[parent]};const boundary='-------314159265358979323846';const body=new Blob(['--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n',JSON.stringify(meta),'\r\n--'+boundary+'\r\nContent-Type: '+(file.type||'application/octet-stream')+'\r\n\r\n',file,'\r\n--'+boundary+'--']);const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink,webContentLink',{method:'POST',headers:{Authorization:'Bearer '+driveToken,'Content-Type':'multipart/related; boundary='+boundary},body});if(!r.ok){if(r.status===401){driveToken=null;throw Error('انتهت صلاحية Google Drive، أعد الربط.')}throw Error('فشل رفع الوثيقة إلى Google Drive.')}return r.json()}
function updateDriveUI(){const b=$('driveConnectBtn');if(b){b.textContent=driveToken?'Google Drive متصل ✓':'ربط Google Drive';b.classList.toggle('primary',!driveToken);b.classList.toggle('ghost',!!driveToken)}}
function init(){const s=$('documents');if(!s)return;const p=s.querySelector('.panel');if(!p||p.dataset.driveReady)return;p.dataset.driveReady='1';p.innerHTML=`<div class="documents-box"><div class="documents-toolbar"><div><h3>الوثائق والأرشيف</h3><p>حفظ وثائق المفتش مباشرة في مساحة Google Drive.</p></div><div class="documents-actions"><button id="driveConnectBtn" class="primary" type="button">ربط Google Drive</button><label class="primary doc-upload-label">+ رفع وثيقة<input id="documentFile" type="file" hidden accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.jpg,.jpeg,.png"></label></div></div><div class="documents-note">يتم إنشاء مجلد باسم «منصة مفتش المادة» في Google Drive وحفظ الوثائق المرفوعة داخله.</div><div id="documentsList" class="documents-list"><div class="empty">اربط Google Drive ثم ارفع أول وثيقة.</div></div></div>`;updateDriveUI();$('driveConnectBtn').onclick=connectDrive;$('documentFile').onchange=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(!driveToken){await connectDrive();if(!driveToken)return}const x=await uploadDrive(f);$('documentsList').innerHTML=`<div class="document-item"><b>${x.name}</b><a href="${x.webViewLink||'#'}" target="_blank" rel="noopener">فتح في Google Drive</a></div>`}catch(err){alert(err.message)}}}
window.initDocumentsDrive=init;document.addEventListener('DOMContentLoaded',init);})();
