(()=>{'use strict';
/* المسار الجديد والوحيد لتحديث الأستاذ - بدون إعادة تحميل متكررة عند تغيير CSS */
const T$=id=>document.getElementById(id);
function client(){return window.__APP_SUPABASE_CLIENT||window.supabaseClient||window.sb||window.supabase?.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY)}
const fields={last_name:'teacherLastName',first_name:'teacherFirstName',rank:'teacherRank',grade:'teacherGrade',institution_id:'teacherInstitution',appointment_date:'teacherAppointmentDate',phone:'teacherPhone',email:'teacherEmail',municipality:'teacherMunicipality',notes:'teacherNotes',status:'teacherStatus',nationality:'teacherNationality',framework:'teacherFramework',scale:'teacherScale',grade_seniority:'teacherGradeSeniority',qualification:'teacherQualification',birth_date:'teacherBirthDate',birth_place:'teacherBirthPlace'};
const labels={teacherLastName:'اللقب',teacherFirstName:'الاسم',teacherRank:'الرتبة',teacherGrade:'الدرجة',teacherInstitution:'المؤسسة',teacherAppointmentDate:'تاريخ التعيين',teacherPhone:'الهاتف',teacherEmail:'البريد الإلكتروني',teacherMunicipality:'البلدية',teacherNotes:'ملاحظات',teacherStatus:'حالة الأستاذ',teacherNationality:'الجنسية',teacherFramework:'الإطار',teacherScale:'السلم',teacherGradeSeniority:'الأقدمية في الدرجة',teacherQualification:'المؤهل العلمي',teacherBirthDate:'تاريخ الميلاد',teacherBirthPlace:'مكان الميلاد'};
function setv(id,v){const e=T$(id);if(e)e.value=v??''}
function labelForInput(id){const e=T$(id);if(!e)return null;return e.closest('label')?.querySelector('span')||e.parentElement?.querySelector(':scope > span')||null}
function stabilizeLabels(){Object.entries(labels).forEach(([id,text])=>{const s=labelForInput(id);if(s&&s.textContent!==text)s.textContent=text});document.querySelectorAll('#teacherForm label').forEach(l=>{const text=(l.textContent||'').replace(/\s+/g,' ').trim();if(/تاريخ\s*ومكان\s*الميلاد/.test(text)){const input=l.querySelector('input');if(input&&input.id!=='teacherBirthDate'&&input.id!=='teacherBirthPlace')l.remove()}})}
function removeCombinedBirth(){document.querySelectorAll('#teacherForm label').forEach(l=>{const text=(l.textContent||'').replace(/\s+/g,' ').trim();if(/تاريخ\s*ومكان\s*الميلاد/.test(text))l.remove()});['teacherBirthDatePlace','teacherBirthDatePlaceInput'].forEach(id=>{const e=T$(id);if(e){const l=e.closest('label');(l||e).remove()}})}
function ensureField(name,label,type,afterId){const id=fields[name];if(T$(id))return T$(id);const anchor=T$(afterId);if(!anchor)return null;const l=document.createElement('label');l.innerHTML=`<span>${label}</span><input id="${id}" name="${name}" type="${type}">`;anchor.closest('label')?.insertAdjacentElement('afterend',l);return T$(id)}
function ensureFields(){removeCombinedBirth();const a=T$('teacherAppointmentDate');if(!a)return;ensureField('birth_date','تاريخ الميلاد','date','teacherAppointmentDate');ensureField('birth_place','مكان الميلاد','text','teacherBirthDate');if(!T$('teacherStatus')){const l=document.createElement('label');l.innerHTML='<span>حالة الأستاذ</span><select id="teacherStatus" name="status"><option value="متربص">متربص</option><option value="طور الترسيم">طور الترسيم</option><option value="مرسم">مرسم</option></select>';a.closest('label')?.insertAdjacentElement('afterend',l)}let anchor='teacherStatus';[['nationality','الجنسية'],['framework','الإطار'],['scale','السلم'],['grade_seniority','الأقدمية في الدرجة'],['qualification','المؤهل العلمي']].forEach(([n,l])=>{ensureField(n,l,'text',anchor);anchor=fields[n]});stabilizeLabels()}
function prepareButton(){const f=T$('teacherForm');if(!f)return;const b=f.querySelector('#teacherUpdateSaveBtn,button[type="submit"]');const id=(T$('teacherId')?.value||'').trim();if(!b)return;b.id='teacherUpdateSaveBtn';b.type='button';b.textContent=id?'حفظ التحديثات':'حفظ';b.onclick=id?save:null}
async function loadTeacher(id){const c=client();if(!c||!id)return;ensureFields();const r=await c.from('teachers').select('id,first_name,last_name,employee_number,rank,subject,institution_id,municipality,appointment_date,grade,phone,email,notes,status,nationality,framework,scale,grade_seniority,qualification,birth_date,birth_place').eq('id',id).maybeSingle();if(r.error){alert('تعذر تحميل بيانات الأستاذ: '+r.error.message);return}if(!r.data){alert('لم يتم العثور على الأستاذ.');return}const t=r.data;Object.entries(fields).forEach(([col,id])=>setv(id,t[col]));const n=T$('teacherEmployeeNumber');if(n)n.textContent=t.employee_number||'—';ensureFields();prepareButton();stabilizeLabels()}
async function save(){const c=client(),id=(T$('teacherId')?.value||'').trim();if(!c)return alert('تعذر الاتصال بقاعدة البيانات.');if(!id)return alert('لم يتم تحديد الأستاذ.');const p={};Object.entries(fields).forEach(([col,id])=>{const e=T$(id);p[col]=e?((String(e.value??'').trim())||null):null});p.subject='التربية البدنية والرياضية';if(!p.last_name||!p.first_name)return alert('يرجى إدخال اللقب والاسم.');const b=T$('teacherUpdateSaveBtn');if(b){b.disabled=true;b.textContent='جارٍ تحديث البيانات...'}try{const r=await c.from('teachers').update(p).eq('id',id).select('id,first_name,last_name,rank,grade,institution_id,appointment_date,phone,email,municipality,notes,status,nationality,framework,scale,grade_seniority,qualification,birth_date,birth_place').maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error('لم يتم تحديث سجل الأستاذ.');alert('تم تحديث بيانات الأستاذ وحفظها في قاعدة البيانات بنجاح.');closeTeacherModal();if(window.loadAll)await window.loadAll()}catch(e){console.error('Teacher update:',e);alert('فشل تحديث بيانات الأستاذ:\n'+(e.message||e))}finally{if(b){b.disabled=false;b.textContent='حفظ التحديثات'}}}
function closeTeacherModal(){const m=T$('teacherModal');if(!m)return;m.hidden=true;m.style.display='none';m.classList.remove('show','open','active');setTimeout(()=>{m.style.display='';m.hidden=true},0)}
function openTeacherModal(){const m=T$('teacherModal');if(!m)return false;m.hidden=false;m.style.display='';m.classList.add('show');return true}
function bind(){const f=T$('teacherForm');if(!f||f.dataset.teacherSaveV6==='1')return;f.dataset.teacherSaveV6='1';ensureFields();prepareButton();const m=T$('teacherModal');if(m&&!m.dataset.teacherSaveV6Observer){m.dataset.teacherSaveV6Observer='1';new MutationObserver(()=>{if(m.hidden){prepareButton();return}stabilizeLabels();prepareButton()}).observe(m,{attributes:true,attributeFilter:['hidden']})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,100));else setTimeout(bind,100);window.teacherSaveV2={bind,loadTeacher,save,openTeacherModal,closeTeacherModal};})();