(()=>{'use strict';
/* مسار مستقل لحفظ ملف الأستاذ - لا يعتمد على أي مسار حفظ قديم */
function client(){try{if(window.__APP_SUPABASE_CLIENT)return window.__APP_SUPABASE_CLIENT;if(window.supabaseClient?.from)return window.supabaseClient;if(window.sb?.from)return window.sb;if(window.supabase?.createClient)return window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY)}catch(e){console.error(e)}return null}
const T$=id=>document.getElementById(id);
const fields={last_name:'teacherLastName',first_name:'teacherFirstName',rank:'teacherRank',grade:'teacherGrade',institution_id:'teacherInstitution',appointment_date:'teacherAppointmentDate',phone:'teacherPhone',email:'teacherEmail',municipality:'teacherMunicipality',notes:'teacherNotes',birth_date:'teacherBirthDate',birth_place:'teacherBirthPlace',status:'teacherStatus',nationality:'teacherNationality',framework:'teacherFramework',scale:'teacherScale',grade_seniority:'teacherGradeSeniority',qualification:'teacherQualification'};
function val(id){const e=T$(id);return e?String(e.value??'').trim():''}
function ensureField(name,type,label,afterId){if(T$(fields[name]))return T$(fields[name]);const anchor=T$(afterId);if(!anchor)return null;const wrap=document.createElement('label');wrap.innerHTML=`${label}<input id="${fields[name]}" name="${name}" type="${type||'text'}>`;anchor.closest('label')?.insertAdjacentElement('afterend',wrap);return T$(fields[name])}
function ensureFields(){const a=T$('teacherAppointmentDate');if(!a)return false;ensureField('birth_date','date','تاريخ الميلاد','teacherAppointmentDate');ensureField('birth_place','text','مكان الميلاد','teacherBirthDate');if(!T$('teacherStatus')){const w=document.createElement('label');w.innerHTML='<span>حالة الأستاذ</span><select id="teacherStatus" name="status"><option value="متربص">متربص</option><option value="طور الترسيم">طور الترسيم</option><option value="مرسم">مرسم</option></select>';a.closest('label')?.insertAdjacentElement('afterend',w)}let anchor='teacherStatus';[['nationality','الجنسية'],['framework','الإطار'],['scale','السلم'],['grade_seniority','أقدمية الدرجة'],['qualification','المؤهل']].forEach(([n,l])=>{ensureField(n,'text',l,anchor);anchor=fields[n]});return true}
async function loadTeacher(id){const c=client();if(!c||!id)return;ensureFields();const r=await c.from('teachers').select('*').eq('id',id).maybeSingle();if(r.error){console.error('Teacher load v2:',r.error);return}const t=r.data;if(!t)return;Object.entries(fields).forEach(([col,id])=>{const e=T$(id);if(e)e.value=t[col]??''});const n=T$('teacherEmployeeNumber');if(n)n.textContent=t.employee_number||'—'}
function payload(){const p={};Object.entries(fields).forEach(([col,id])=>{const e=T$(id);if(!e)return;const v=String(e.value??'').trim();p[col]=v===''?null:v});return p}
async function save(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const f=e.currentTarget;ensureFields();const id=val('teacherId');const c=client();if(!c)return alert('تعذر الاتصال بقاعدة البيانات.');if(!id)return alert('تعذر تحديد الأستاذ المراد تعديله.');const p=payload();if(!p.last_name||!p.first_name)return alert('يرجى إدخال اللقب والاسم.');const b=f.querySelector('button[type="submit"]');if(b){b.disabled=true;b.dataset.oldText=b.textContent;b.textContent='جارٍ حفظ التعديلات...'}try{const r=await c.from('teachers').update(p).eq('id',id).select('id').maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error('لم يتم تحديث أي سجل للأستاذ.');alert('تم حفظ تعديلات الأستاذ بنجاح.');const m=T$('teacherModal');if(m)m.hidden=true;if(typeof window.loadAll==='function')await window.loadAll()}catch(err){console.error('Teacher save v2:',err);alert('تعذر حفظ تعديلات الأستاذ:\n'+(err?.message||err))}finally{if(b){b.disabled=false;b.textContent=b.dataset.oldText||'حفظ'}}}
function bind(){const f=T$('teacherForm');if(!f||f.dataset.teacherSaveV2==='1')return;f.dataset.teacherSaveV2='1';ensureFields();f.addEventListener('submit',save,true);const m=T$('teacherModal');if(m&&!m.dataset.teacherLoadV2){m.dataset.teacherLoadV2='1';const observer=new MutationObserver(()=>{if(!m.hidden){ensureFields();const id=val('teacherId');if(id&&m.dataset.loadedTeacherV2!==id){m.dataset.loadedTeacherV2=id;loadTeacher(id)}}});observer.observe(m,{attributes:true,attributeFilter:['hidden']})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,100));else setTimeout(bind,100);window.teacherSaveV2={bind,loadTeacher,save};
})();